### PR TITLE
Trainee dashboards

### PR DESCRIPTION
**Pull request by aditipate**
**This PR adds the following dashboards:**

**- dash-manhattan-plot** 
Plotly Dash dashboard the utilizes the Plotly Dash Bio Suite to present an interactive Manhattan plot, allowing users to explore GWAS data. Includes a slider to modify the Genome Wide Significance threshold and a Dash table to display top SNPs and their associated gene/gene summaries. 

**- streamlit-stroke-predictor** 
Streamlit dashboard includes a stroke predictor form containing fields for determinants of stroke. A user can provide this data for a hypothetical individual, which are then used by a classifier to predict the likelihood of the individual experiencing stroke. 

**- polus-flatfield-comparison-streamlit**
Streamlit dashboard allows users to select a pair of images consisting of a raw and flat field corrected image. Images are displayed side by side using the Streamlit Image Comparison component so that they may be compared by adjusting a slider, overall enhancing the ability to visualize differences.

### CODE REVIEW

**Comment by ktaletsk** [comment]
What is the purpose of `prototypes/polus-flatfield-comparison-streamlit/temp` folder? Is it being used anywhere in the code? If not, please remove it

**Comment by ktaletsk** [comment]
I think it does not make sense to include the whole original/corrected dataset in this PR, it takes lots of data and makes GitHub slow/broken when opening the code review page. I think, @aditipate should take a look at these images, find 5 most interesting pairs and only leave them, deleting the rest of the dataset.

FYI, in the next version of this dashboard, we will be working with external datasets and processing on the fly, so we won't need this pre-processed data.

**Comment by aditipate** [comment]
> What is the purpose of `prototypes/polus-flatfield-comparison-streamlit/temp` folder? Is it being used anywhere in the code? If not, please remove it

**Comment by aditipate** [comment]
> What is the purpose of `prototypes/polus-flatfield-comparison-streamlit/temp` folder? Is it being used anywhere in the code? If not, please remove it

I believe this is a temporary folder generated by the tifffile package either when normalizing/converting the ome.tiff images or when uploading them to store the image pair, however I don't think the folder is needed in the code so I'll update that

**Comment by aditipate** [comment]
> I think it does not make sense to include the whole original/corrected dataset in this PR, it takes lots of data and makes GitHub slow/broken when opening the code review page. I think, @aditipate should take a look at these images, find 5 most interesting pairs and only leave them, deleting the rest of the dataset.
> 
> FYI, in the next version of this dashboard, we will be working with external datasets and processing on the fly, so we won't need this pre-processed data.

That makes sense, I'll update the data folders to only contain 5 and try to include those that are the most interesting

**Comment by aditipate** [comment]
Additional changes made:
- deleted extra images from data, now only contains 5 sample images 
- deleted the temp folder generated by tiffile

**Review by ktaletsk — CHANGES_REQUESTED** [review]
Could you add README.md file into each of these new dashboard folders?
This would be a good place to give a short description of each example and indicate the origin/link to the data and any license for the dataset used.

**Comment by aditipate** [comment]
Added a README to the following:
* dash-manhattan-plot
* streamlit-stroke-predictor
* polus-flatfield-comparison-streamlit

Includes dashboard descriptions and links to datasets as well as other resources.

**Pull request closed without merging**
